import type { Element } from "@/types/bazi";

export const SPIRITUAL_ROOT_RULES = {
  presence: {
    visibleStemMass: 30,
    branchMass: 30,
    // 지장간 작용 일수에는 유파 차가 커, 글자 수별 비율을 명시한 설명용 모델을 쓴다.
    branchShares: {
      single: { main: 1, middle: 0, residual: 0 },
      double: { main: 0.7, middle: 0.3, residual: 0 },
      triple: { main: 0.6, middle: 0.3, residual: 0.1 },
    },
  },
  scores: {
    dayMaster: 3,
    monthBranchMain: 4,
    visibleStem: 2,
    branchMain: 2,
    // 지지 본기 점수에 같은 지장간 본기를 다시 더하지 않는다.
    hiddenMain: 0,
    hiddenMiddle: 0.75,
    hiddenResidual: 0.25,
    fullHarmony: 4,
    directionalHarmony: 4,
    halfHarmony: 2,
    archingHarmony: 0.5,
    sixHarmony: 1,
    transformedStemCombination: 3,
    strongSupport: 1,
    rootedSourceSupport: 0.5,
    seasonalProsperous: 2,
    seasonalAssistant: 1,
    seasonalImprisoned: -0.5,
    seasonalDead: -1,
    flowingGeneration: 0.75,
    mediationPassage: 1,
    monthCommandBonus: 2,
    uniqueRootClash: -2,
    seasonalExtremeWeakness: -1,
    uncontrolledStrongControl: -2,
    stemWithoutRoot: -1,
    combinedAway: -1,
    combinedBinding: -0.5,
    rootedControlMitigation: 0.75,
  },
  thresholds: {
    independentStrength: 4,
    potential: 2,
    generousChannel: 4,
    // 저점 실근 예외는 이 값을 엄격히 초과해야 하며 0점은 허용하지 않는다.
    groundedTraceFloor: 0,
    balanceGap: 2,
    strongBiasGap: 3.5,
    heavenlyPurityGap: 14,
    heavenlySecondaryMax: 3.5,
    heavenlyPrimaryMin: 18,
    fiveBalanceSpread: 3,
  },
  roots: {
    roleStrength: {
      main: 1,
      middle: 0.45,
      residual: 0.2,
    },
    positionMultiplier: {
      year: 0.9,
      month: 1.25,
      day: 1.1,
      hour: 1,
    },
    clashMultiplier: 0.45,
    visibleConnectionMinimum: 0.6,
    dayMasterMinimum: 0.6,
    strongRootMinimum: 0.8,
  },
  structure: {
    effectiveScore: 4,
    potentialScore: 2,
    supportSourceScore: 4,
    supportTargetBaseScore: 1.5,
    flowSourceScore: 4,
    flowTargetScore: 4,
    mediationSideScore: 4,
    mediationElementScore: 4,
    strongControllerScore: 6,
    weakRescueScore: 4,
    collectiveMaximumSpread: 24,
    collectiveBuriedMaximumSpread: 14.5,
    collectiveModerateGap: 22,
    collectiveHostileSpread: 16,
    compoundConstraintFloor: -2.25,
    rootedPotentialMinimum: 0.6,
  },
  channelGates: {
    heavenMinimum: 2,
    earthMinimum: 1.1,
    humanMinimum: 2,
    integrityMinimum: 0.45,
    activationMinimum: 4,
    strongHeaven: 6,
    strongEarth: 6,
    strongHuman: 5,
    strongActivation: 15,
    bottleneckWeight: 0.65,
    averageWeight: 0.35,
    mixedNetworkMinimum: 3,
    carriedActivationMinimum: 2,
    carriedIntegrityMinimum: 0.6,
  },
  mutationStatus: {
    confirmed: 80,
    likely: 65,
    possible: 50,
  },
  multiRootProfiles: {
    dominantSpread: 5,
    mixedConflictMinimum: 2,
    turbulentConflictMinimum: 4,
    fourStrongFlowMinimum: 3,
    fiveStrongFlowMinimum: 4,
    completeCycleLinks: 5,
    // 다섯 기맥을 함께 보존할 수 있는 오영근 예외형. 나머지 다근은 약근 정련을 기본으로 한다.
    preserveAllFiveSubtypes: ["오기조원형", "오행원융형", "정적균형형"],
  },
  stemCombination: {
    requireAdjacency: true,
    requireDayStemForTransformation: true,
    originalRootResistanceMaximum: 1.25,
  },
  awakening: {
    populationRates: {
      generous: 100,
      balanced: 13.2,
      strict: 1,
    },
  },
  daoAffinity: {
    natural: {
      monthCommand: 12,
      dayRoot: 4,
      daySupport: 6,
      visibleAndRooted: 2,
      generatingLink: 3,
      completeCycle: 6,
      fullFormation: 6,
      halfFormation: 2,
      stemCombination: 3,
      mediation: 4,
      clearBalance: 6,
      quietStructure: 6,
      conflictPenalty: -2,
      rootlessPenalty: -10,
    },
    defiant: {
      hostileSeason: 12,
      againstCommand: 4,
      dayRoot: 4,
      daySupport: 6,
      extremeDominance: 10,
      dominantGap: 8,
      dynamicStructure: 3,
      rescuedConflict: 8,
      formation: 5,
      strengthAgainstSeason: 8,
      controlledButRooted: 6,
      rootlessPenalty: -12,
    },
  },
  grade: {
    lowMax: 6.9,
    middleMax: 9.9,
    highMax: 12.9,
    supremeMin: 13,
  },
  rawStrength: {
    strongSupport: 2,
    strongControl: 3,
    rescue: 1.5,
  },
} as const;

export const SEASON_DOMINANT: Record<string, Element> = {
  spring: "wood",
  summer: "fire",
  earth: "earth",
  autumn: "metal",
  winter: "water",
};

export const SEASON_EXTREME_WEAK: Record<string, Element> = {
  spring: "earth",
  summer: "metal",
  earth: "water",
  autumn: "wood",
  winter: "fire",
};
