import type { Metadata } from "next";
import { InfoPageShell, InfoSection } from "@/components/InfoPageShell";

export const metadata: Metadata = { title: "영근 판정 기준" };

export default function GuidePage() {
  return <InfoPageShell eyebrow="Judgement guide" title="영근은 어떻게 판정하나요?" intro="오행의 단순 개수가 아니라, 사주 안에서 실제로 뿌리내리고 드러나 영기를 흡수할 통로를 이루는지 평가합니다.">
    <InfoSection title="천·지·인 삼관으로 영근을 찾습니다" marker="一"><div className="grid gap-3 sm:grid-cols-3"><div><strong className="text-[#9fc0e8]">천문 天</strong><p className="mt-2">천간 투출, 월령의 감응, 합국·합화처럼 기운이 바깥 영기와 접속하는 발현구를 봅니다.</p></div><div><strong className="text-[#a9c991]">지근 地</strong><p className="mt-2">지지 본기와 지장간의 통근, 월지, 합국, 충손을 보아 기운을 저장할 뿌리를 찾습니다.</p></div><div><strong className="text-[#dfc57f]">인맥 人</strong><p className="mt-2">일간과의 생극 관계, 생조·유통·통관을 보아 그 기운을 단전에서 운용할 수 있는지 봅니다.</p></div></div><p className="mt-3 text-xs text-[#778c94]">세 관문과 기맥 보존성·활성도가 함께 이어져야 완성 영근입니다. 투출만 있으면 부유맥, 지장간에만 있으면 은근맥, 세 관문은 있으나 힘이 모자라면 봉맥으로 남습니다.</p></InfoSection>
    <InfoSection title="판정 모드는 선천 기감 관문을 바꿉니다" marker="二"><p><strong className="text-[#e0ce9f]">유연 판정</strong>은 완성된 삼관 기맥이 하나라도 있으면 그대로 발현시키는 기본값입니다. <strong className="text-[#e0ce9f]">균형 판정</strong>은 태원→태식→명궁의 납음이 동기 또는 순생하고 인접한 두 흐름에 직접 충이 없어야 합니다. <strong className="text-[#e0ce9f]">엄격 판정</strong>은 여기에 세 보조축 전체가 합·동기로 연결되고, 실제 천간합·지지육합이 하나 이상 있으며, 충·해·파의 파손이 없어야 선천일기가 응결합니다. 관문을 통과한 뒤의 영근 종류와 개수는 유연 판정과 같습니다. 50,000개 고정 검증 표본에서 균형 13.24%, 엄격 0.994%가 통과했습니다.</p></InfoSection>
    <InfoSection title="순천·역천은 각성 뒤의 수련 성향입니다" marker="三"><div className="grid gap-3 sm:grid-cols-2"><div><strong className="text-[#9fc0e8]">순천도맥</strong><p className="mt-2">득령·통근·생조와 상생 유통이 자연스럽게 이어져 천지의 기세를 따라 수련하는 경로입니다.</p></div><div><strong className="text-[#dfc57f]">역천도맥</strong><p className="mt-2">역령·충형·극쇠 속에서도 뿌리와 구원이 남거나 편기가 돌파력을 얻어 불리한 흐름을 뒤집는 경로입니다.</p></div></div><p className="mt-3 text-xs text-[#778c94]">도맥은 영근 유무나 개수를 결정하지 않습니다. 같은 영근이라도 어떤 방식으로 성장하는지를 설명하는 선협용 후천 성향입니다.</p></InfoSection>
    <InfoSection title="구성량과 활성도는 다릅니다" marker="四"><p>먼저 4천간과 4지지를 합계 240의 고정 질량으로 환산해 원국 구성비를 보여 줍니다. 그 뒤 월령, 왕·상·휴·수·사, 본·중·여기 통근, 투간, 생조·극제와 합충을 적용해 별도의 기맥 활성도를 냅니다. 따라서 구성비가 분명히 존재해도 계절과 극제 때문에 활성 영근이 되지 못할 수 있으며, 이는 그 오행이 원국에서 0이라는 뜻이 아닙니다.</p></InfoSection>
    <InfoSection title="활성·응축·융합을 구조로 판정합니다" marker="五"><div className="grid gap-3 sm:grid-cols-2"><ul className="list-disc pl-5"><li>월령과 왕·상·휴·수·사</li><li>본기·중기·여기의 가중 통근</li><li>투간과 뿌리의 실제 연결</li><li>삼합·방합·반합·공합 구분</li></ul><ul className="list-disc pl-5"><li>성립된 기맥에서만 생조·유통</li><li>강한 중간 오행만 통관 인정</li><li>합이불화와 완전 합화 구분</li><li>겹친 합거·극제 감점에 상한 적용</li></ul></div><p className="mt-3 text-xs text-[#778c94]">천영근은 주근 18점 이상·부근 3.5점 이하·격차 14점 이상을 모두 만족할 때만 응축됩니다. 변이는 두 유효 원재료와 실제 생극·계절·동세·방해 조건을 평가하며 제3 유효 영근이 있으면 확정되지 않습니다. 해시나 난수로 영근 수를 배분하지 않습니다.</p></InfoSection>
    <InfoSection title="사·오영근도 내부 구조가 다릅니다" marker="六"><div className="grid gap-4 sm:grid-cols-2"><div><strong className="text-[#e0ce9f]">사영근 세부형</strong><p className="mt-2">결핍 오행과 주도 기맥을 함께 표시합니다. 점수 편차·상생 고리·충극 강도에 따라 주근편중형, 균형순생형, 사상균형형, 순생연쇄형, 충극교차형, 다맥병립형으로 나뉩니다.</p></div><div><strong className="text-[#e0ce9f]">오영근과 오기조원</strong><p className="mt-2">다섯 기맥이 모두 있어도 운용법은 다릅니다. 목→화→토→금→수→목의 실제 생조 고리 다섯 개가 모두 이어지면 오기조원영근이 되며, 편차와 충극에 따라 유통·편기·탁류·원융으로 나뉩니다.</p></div></div><p className="mt-3 text-xs text-[#778c94]">오기조원의 자격은 상생환 완성으로 판정하고, 최고·최저 기맥의 활성 편차와 충·형·파·해는 순환의 세부형과 주의점을 정합니다. 단순한 문구 추첨이 아닙니다.</p><p className="mt-3">일반적인 다근은 약한 기맥을 더 깨우지 않고 봉근·세맥하여 주근에 영기를 모으는 쪽을 상위 정련으로 봅니다. 결핍 속성이 필요하면 몸 안에 새 영근을 만들기보다 법보·진법으로 빌립니다. 오행균형과 오기조원 계열은 다섯 기맥을 함께 보존하되, 편기와 충손을 다스려 원융하게 정련합니다.</p></InfoSection>
    <InfoSection title="신살은 다섯 재능 축으로 번역합니다" marker="七"><div className="grid gap-3 sm:grid-cols-5"><div><strong className="text-[#e0ce9f]">근골</strong><p className="mt-2">영근·체질 기반</p></div><div><strong className="text-[#e0ce9f]">오성</strong><p className="mt-2">이해·추연·융합</p></div><div><strong className="text-[#e0ce9f]">투골 鬪骨</strong><p className="mt-2">실전·폭발·통솔</p></div><div><strong className="text-[#e0ce9f]">신혼</strong><p className="mt-2">정신·환술·도심</p></div><div><strong className="text-[#e0ce9f]">기운</strong><p className="mt-2">기연·귀인·호도</p></div></div><p className="mt-3">문창·태극·화개는 오성과 참오, 양인·괴강·장성은 전투 자질, 귀문은 신혼 감응, 천을·천덕·월덕은 호도와 기운에 연결합니다. 천교는 뛰어난 근골과 보조 재능이 함께 있어야 하며 천도지자는 여러 귀인성이 겹친 극희귀 호도형입니다. 성자·도자는 종문이 임명하는 지위라 여기서 판정하지 않습니다.</p></InfoSection>
    <InfoSection title="희귀도와 모호함을 함께 검증합니다" marker="八"><p>5,000개 고정 표본의 유연 판정에서는 천영근 1.34%, 변이영근 3.78%, 이영근 7.16%, 삼영근 25.02%, 사영근 36.36%, 오영근 26.34%였습니다. 오기조원영근은 전체 79명(1.58%), 오영근 중 약 6.0%로 나타났습니다. 이는 규칙의 희귀 순서와 특수 순환형의 실제 도달 가능성을 함께 확인하는 회귀 표본입니다. 선천 기감 조건, 절기·시진 경계, 출생 시각 불확실성, 비슷한 변이 후보는 판정 신뢰도를 낮춥니다.</p></InfoSection>
  </InfoPageShell>;
}
