import type { Metadata } from "next";
import Link from "next/link";
import { InfoPageShell, InfoSection } from "@/components/InfoPageShell";

export const metadata: Metadata = { title: "계산법과 한계" };

export default function MethodologyPage() {
  return <InfoPageShell eyebrow="Methodology" title="계산법과 한계" intro="달력 계산의 기준, 시간 보정 방식, 라이브러리 선택과 불확실성을 투명하게 공개합니다.">
    <InfoSection title="네 기둥 산출"><ul className="list-disc pl-5"><li>연주는 양력 1월 1일이 아니라 정확한 입춘 시각에 바뀝니다.</li><li>월주는 음력 월이 아니라 12절기의 절입 시각과 오호둔을 따릅니다.</li><li>일주는 검증된 중국력 라이브러리의 율리우스일 기반 60갑자 계산을 사용합니다.</li><li>시주는 현지의 2시간 시진과 일간에 따른 오서둔을 사용합니다.</li><li>야자시를 켜면 보정된 현지 시각 23시부터 일주를 다음 날로 봅니다.</li></ul></InfoSection>
    <InfoSection title="시간대와 절기 시각"><p>입력 시각은 Luxon과 실행 환경의 IANA 시간대 데이터로 실제 순간(UTC)을 구합니다. <code className="text-[#e0ce9f]">lunar-typescript</code>의 절기표는 중국 표준시 표현이므로 같은 순간을 <code className="text-[#e0ce9f]">Asia/Shanghai</code>로 변환해 입춘·절입 경계를 비교합니다. 일주와 시주는 선택한 출생지의 보정된 현지 벽시계를 사용합니다.</p></InfoSection>
    <InfoSection title="진태양시"><p>옵션을 켰을 때만 <code className="text-[#e0ce9f]">4 × (출생지 경도 − 표준 자오선)</code>분의 경도 보정과 <code className="text-[#e0ce9f]">9.87 sin(2B) − 7.53 cos(B) − 1.5 sin(B)</code>분의 균시차 근사식을 더합니다. B는 <code className="text-[#e0ce9f]">2π(연중일−81)/364</code>입니다. 도시 중심 경도는 결과에 근사값으로 표시됩니다.</p></InfoSection>
    <InfoSection title="영근 삼관과 선천 기감"><p>각 오행은 천문(투출·월령 감응·합국 발현), 지근(본·중·여기 통근과 충손), 인맥(일간과의 생극·생조·유통·통관)을 따로 계산합니다. 세 관문과 기맥 보존성·활성도가 모두 이어져야 완성 기맥입니다. 유연은 완성 기맥을 바로 발현시킵니다. 균형·엄격은 영근 수를 다시 계산하지 않고 태원·태식·명궁의 납음 유통과 간지 결속만 별도 관문으로 확인합니다. 50,000개 고정 검증 표본에서 균형 13.24%, 엄격 0.994%가 통과했으며, 통과자의 영근 분포는 유연의 희귀 순서를 유지했습니다.</p><p className="mt-3">근골은 영근의 현재 발현 여부가 아니라 선천 기맥 구조와 순도·완성도가 육신에 남긴 잠재치입니다. 따라서 균형·엄격 관문에서 영문이 열리지 않아 실제 영근이 미각성으로 표시되더라도, 같은 명식의 근골은 유연 판정과 동일하게 보존합니다. 천교·천도지자와 실제 영근 수련 효과는 여전히 발현 관문을 통과해야 합니다.</p></InfoSection>
    <InfoSection title="태원·태식·명궁 산출"><p>태원은 월주에서 천간을 한 자리, 지지를 세 자리 순행해 구합니다. 태식은 일간의 오합 상대와 일지의 육합 상대를 짝지으며, 명궁은 월지와 시지를 배치한 뒤 연간으로 궁간을 세웁니다. 각 보조주의 납음오행이 태원→태식→명궁으로 동기·순생하는지를 보고, 엄격에서는 세 축의 천간합·지지육합·동간·동지 연결과 충·해·파를 함께 확인합니다. <Link className="text-[#dfc57f] underline underline-offset-4" href="https://zh.wikisource.org/zh-hant/%E4%B8%89%E5%91%BD%E9%80%9A%E6%9C%83/%E5%8D%B7%E4%BA%8C">《삼명통회》 권2</Link>의 태원·명궁 관점과 사용 라이브러리의 보조주 산식을 따릅니다.</p></InfoSection>
    <InfoSection title="도맥은 후천 수련 성향"><p>순천도맥은 득령·득지·생조, 상생 유통·통관, 합국과 안정성이 자연스럽게 이어지는 경로입니다. 역천도맥은 역령·충형·극쇠 속에서도 통근과 구원이 남거나 편기 집중이 돌파력을 얻는 경로입니다. 두 도맥은 각성한 영근을 어떻게 수련하는지 설명할 뿐 영근 유무·개수·품질을 결정하지 않습니다.</p></InfoSection>
    <InfoSection title="원국 구성과 기맥 활성"><p>오행이 있다는 사실과 실제 세력을 한 숫자로 섞지 않습니다. 설명용 원국 구성은 천간마다 30, 지지마다 30으로 두고 지장간이 하나면 100%, 둘이면 본기 70%·중기 30%, 셋이면 본기 60%·중기 30%·여기 10%로 나눠 합계 240의 구성비를 냅니다. 이는 공인된 명리 퍼센트가 아니라 재료의 존재를 누락하지 않기 위한 고정 모델입니다. 기맥 활성도는 이와 별도로 월령·왕쇠·통근·투출·생극·합충을 적용합니다.</p></InfoSection>
    <InfoSection title="구조 유효성과 순도"><p>지지 본기와 같은 지장간 본기는 활성도에서 중복 가산하지 않습니다. 본기·중기·여기는 위치와 충손을 반영한 가중 통근으로 바꾸며, 생조 공급원과 통관의 중간 오행은 먼저 자체 기맥이 있어야 합니다. 왕지가 빠진 두 글자는 정식 반합이 아닌 공합 후보입니다. 일반 공동 유통은 활성 2점 이상을 요구합니다. 유연 판정에서는 활성 2점 이상인 기맥 세 개가 망을 지탱할 때 활성도가 0점을 넘고 실제 통근이 남은 저점 기맥도 인정합니다. 세 완성 기맥이 별도 통로를 운반할 때는 2점 이상의 잠재근을 요구하고, 저점 실근은 네 기맥이 이미 열린 경우에만 추가 연결합니다. 0점·무근 흔적은 유효 영근으로 승격하지 않습니다. 천영근 응축은 주근 18점·부근 3.5점·격차 14점 관문을 모두 통과해야 하며, 강한 제2 영근을 단순 역치 탈락으로 지우지 않습니다. 변이 확정선은 80점이고 제3 유효 영근이 있으면 최대 69점으로 제한됩니다.</p></InfoSection>
    <InfoSection title="천간합과 합화"><p>천간 두 글자가 보인다는 이유만으로 합화시키지 않습니다. 이 구현은 보수적으로 인접, 일간 참여, 화신이 월령 또는 완성 합국을 얻음, 원래 오행의 가중 뿌리가 1.25 이하라는 조건을 모두 요구합니다. 부족하면 ‘합이불화’로 두고 독립 작용만 소폭 낮춥니다. 합거와 강한 극제가 같은 기맥을 동시에 누를 때는 중복 감점 하한을 적용합니다.</p></InfoSection>
    <InfoSection title="신살과 선협 재능"><p>신살은 영근 유무·개수·품질을 바꾸지 않고 수련 성향에만 사용합니다. 연지·일지의 삼합군으로 화개·역마·장성·도화·겁살을 찾고, 귀문은 여섯 지지쌍을 사용합니다. 천을귀인은 연간·일간, 문창·양인은 일간, 천덕·월덕은 월지를 기준으로 보며 괴강은 경진·경술·임진·무술 일주만 인정합니다. 기본 고전 기준의 태극귀인은 연간에서 찾고, 양인은 갑·병·무·경·임의 다섯 양간만 봅니다. 확장 기준을 선택하면 일간 태극과 음간의 제왕지를 ‘음인’으로 구분해 더합니다. <Link className="text-[#dfc57f] underline underline-offset-4" href="https://zh.wikisource.org/zh-hant/%E4%B8%89%E5%91%BD%E9%80%9A%E6%9C%83/%E5%8D%B7%E4%B8%89">《삼명통회》 권3</Link>의 귀인·덕성 표와 <Link className="text-[#dfc57f] underline underline-offset-4" href="https://zh.wikisource.org/zh-hans/%E6%B7%B5%E6%B5%B7%E5%AD%90%E5%B9%B3">《연해자평》</Link>의 양인 구분을 기준표의 뼈대로 삼았습니다.</p><p className="mt-3">표에 맞는 글자가 있더라도 곧바로 같은 효력으로 보지 않습니다. 어느 주에 놓였는지, 몇 자리에 반복되는지로 작용도를 계산하고, 그 자리가 충·형·파·해를 받으면 보존도를 낮춥니다. 보존도가 크게 무너진 길성은 재능 가산과 특수 칭호 조건에서 제외하며, 살성·혼합성의 충손은 억제보다 격동성과 위험을 높이는 쪽으로 반영합니다.</p><p className="mt-3">선협 재능은 근골·오성·투골·신혼·기운의 다섯 축으로 분리합니다. 근골은 영근 구조에서, 나머지는 유효하게 작용하는 신살의 상징적 성향과 충형 동세에서 계산합니다. 천교는 우수한 근골과 오성·전투·신혼 중 하나가 함께 높아야 하며, 천도지자는 천을과 천덕·월덕을 포함한 다중 호도와 실제 영근 각성을 함께 요구합니다. 성자·도자는 종문 직위이므로 판정하지 않습니다.</p></InfoSection>
    <InfoSection title="명리 개념의 적용"><p><Link className="text-[#dfc57f] underline underline-offset-4" href="https://zh.wikisource.org/wiki/%E6%BB%B4%E5%A4%A9%E9%AB%94">《적천수》</Link>의 계절 기세·오행 순역과 <Link className="text-[#dfc57f] underline underline-offset-4" href="https://zh.wikisource.org/wiki/%E6%BB%B4%E5%A4%A9%E9%AB%94%E9%97%A1%E5%BE%AE">《적천수천미》</Link>의 생화 유통·막힘·구원 관점, <Link className="text-[#dfc57f] underline underline-offset-4" href="https://zh.wikisource.org/zh-hant/%E4%B8%89%E5%91%BD%E9%80%9A%E6%9C%83/%E5%8D%B7%E4%BA%8C">《삼명통회》 권2</Link>의 합과 화, 태원과 명궁 관점을 참고했습니다. 원국에 재료가 존재하는 것, 계절 속에서 세력을 얻는 것, 선천 기감으로 발현되는 것을 구분해 구성비·삼관·삼원·도맥으로 잇습니다.</p></InfoSection>
    <InfoSection title="사용 라이브러리와 라이선스"><p><Link className="text-[#dfc57f] underline underline-offset-4" href="https://github.com/6tail/lunar-typescript">lunar-typescript 1.8.6</Link>은 양·음력/윤달, 절기표와 팔자 Exact 계열을 제공하는 MIT 라이선스 라이브러리입니다. 시간대 정규화에는 MIT 라이선스의 <Link className="text-[#dfc57f] underline underline-offset-4" href="https://moment.github.io/luxon/">Luxon 3.7.2</Link>을 사용합니다. 브라우저 밖의 만세력 API는 호출하지 않습니다.</p></InfoSection>
    <InfoSection title="남아 있는 한계"><ul className="list-disc pl-5"><li>명리학의 야자시·신살·합화 판정은 유파마다 다릅니다.</li><li>태극의 일간 병용과 음간 제왕지 해석은 확장 기준으로 분리했으며, 음간을 양인으로 부르지 않습니다.</li><li>신살의 작용도·보존도는 고전의 왕쇠·충파 관점을 일관된 화면 수치로 옮긴 해석 모델입니다.</li><li>1900~2100년 범위만 UI에서 지원합니다.</li><li>역사적 표준시와 서머타임은 실행 환경의 IANA 데이터 품질에 영향을 받습니다.</li><li>균시차는 항해용 정밀 천문력이 아닌 일반 근사식입니다.</li><li>30분 경계 경고는 설정 민감도를 알리는 보수적 기준입니다.</li></ul></InfoSection>
  </InfoPageShell>;
}
